// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlkysxnucmsefnekktkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsa3lzeG51Y21zZWZuZWtrdGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNTU2MzIsImV4cCI6MjA1NzYzMTYzMn0.XWETlxQ_w09bK8tsFUvyTkcVpaUpXQ0e5_i95rPB4zE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);