// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shbrovosiycfwyubgazc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoYnJvdm9zaXljZnd5dWJnYXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTM4NzYsImV4cCI6MjA2MjMyOTg3Nn0.A0CrNJN490YUv8uq6u2rHgw_RM98PPYOqESawFzT-V4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);